name: stickerz
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.1

dependencies:
  archive: ^4.0.9
  bloc: ^9.1.0
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_bicubic_resize: ^1.5.3
  freezed_annotation: ^3.1.0
  get_it: ^9.2.1
  image_picker: ^1.2.2
  path: ^1.9.1
  pro_image_editor: ^13.3.1
  share_plus: ^13.3.0

dev_dependencies:
  build_runner: ^2.15.0
  freezed: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.8

flutter:
  uses-material-design: true
  assets:
    - assets/
